upstream news_feed_app {
    server news-feed-app-1:8080;
    server news-feed-app-2:8080;
}

server {
    listen 80;

    location / {
        proxy_pass http://news_feed_app;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_connect_timeout 5s;
        proxy_read_timeout 30s;
    }

    location /health {
        return 200 'OK';
        add_header Content-Type text/plain;
    }
}
